# Config file
# NOTE: DON'T change any of the things not in quotations, this will cause the plugin to not be able to grab the format.
# Another note: The prefix is in front of 'Message', 'ReloadMessage', and 'NoPermissionButTried'

# Placeholders, what they do, and what they are available for
# %player%: Is the players name that sent the message or issued the command. Available for 'Message' and 'NoPermissionButTried'
# %message%: The message that was attached to the '/ao' command. Available for 'Message' and 'NoPermissionButTried'
# %playerworld%: The world that the player who issued the '/ao' command. Only available for 'Message'
AdminOnly:


  Prefix: '&f[&d&lA&9&lO&f]'
  InvalidUsageMessage: '&4You do not have access to this command!'
  Message: '&2%playerworld% &9%player%: &b%message%'
  ReloadMessage: '&bConfig Reloaded'
  NoPermissionMessage: '&4You do not have permission to run this command!'
  NoPermissionButTried: '&9%player% tried to speak in AO but was denied with message: &b%message%'
