#Basic Configuration For AdminOnly Plugin!
AdminOnly:
  Prefix: '&f[&d&lA&9&lO&f]'
  InvalidUsageMessage: '&4You do not have access to this command!'
  Message: '&2%playerworld% &9%player%: &b%message%'
    #The tag %player% represents the players username.
    #The tag %message% represents the message that the player is sending. (I.E. '/ao <message>' in which <message> is the %message%)
    #The tag &playerworld% is the world the player is currently in
  ReloadMessage: '&bConfig Reloaded'
