main: com.falsegamer.AdvancedAdminChat.Main
version: 1.5
name: AdvancedAdminOnly
description: Hunters Advanced Admin Chat plugin based off of AdminOnly
author: thefalsegamer4

commands:
  ao:
    usage: /ao <message>
    description: Sends a message to admins!
  aoreload:
    description: Reloads the AO config
